// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
//std::shared_ptr<DoubleSolenoid> RobotMap::mainSubsystemLiftSolenoidDouble;
std::shared_ptr<Solenoid> RobotMap::solenoid0;
std::shared_ptr<Solenoid> RobotMap::solenoid1;
std::shared_ptr<Solenoid> RobotMap::solenoid4;
std::shared_ptr<Solenoid> RobotMap::solenoid5;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    //mainSubsystemLiftSolenoidDouble.reset(new DoubleSolenoid(0, 0, 1));
    //lw->AddActuator("MainSubsystem", "LiftSolenoidDouble", mainSubsystemLiftSolenoidDouble);
    
    solenoid0.reset(new Solenoid(0));
    solenoid1.reset(new Solenoid(1));
    solenoid4.reset(new Solenoid(4));
    solenoid5.reset(new Solenoid(5));


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
