// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef MAINSUBSYSTEM_H
#define MAINSUBSYSTEM_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class MainSubsystem: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<DoubleSolenoid> liftSolenoidDouble;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	MainSubsystem();
	void InitDefaultCommand();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	//std::shared_ptr<DoubleSolenoid> armSol;
	std::shared_ptr<Solenoid> shooterSol1;
	std::shared_ptr<Solenoid> shooterSol2;
	std::shared_ptr<Solenoid> armSol1;
	std::shared_ptr<Solenoid> armSol2;

	bool solStates[2];

	void moveShooter(std::shared_ptr<Joystick> rightJoystick);
	void stopShooter();
	void moveArm(std::shared_ptr<Joystick> leftJoystick);
	void stopArm();
};

#endif
